// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { healthHealth, type Options, ordersCreateOrder, ordersPayOrder, productsCreateProduct, productsGetProduct, productsListProducts } from '../sdk.gen';
import type { HealthHealthData, HealthHealthResponse, OrdersCreateOrderData, OrdersCreateOrderError, OrdersCreateOrderResponse, OrdersPayOrderData, OrdersPayOrderError, OrdersPayOrderResponse, ProductsCreateProductData, ProductsCreateProductError, ProductsCreateProductResponse, ProductsGetProductData, ProductsGetProductError, ProductsGetProductResponse, ProductsListProductsData, ProductsListProductsError, ProductsListProductsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const productsListProductsQueryKey = (options?: Options<ProductsListProductsData>) => createQueryKey('productsListProducts', options);

/**
 * List Products
 *
 * List products, newest first.
 */
export const productsListProductsOptions = (options?: Options<ProductsListProductsData>) => queryOptions<ProductsListProductsResponse, ProductsListProductsError, ProductsListProductsResponse, ReturnType<typeof productsListProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await productsListProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsListProductsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const productsListProductsInfiniteQueryKey = (options?: Options<ProductsListProductsData>): QueryKey<Options<ProductsListProductsData>> => createQueryKey('productsListProducts', options, true);

/**
 * List Products
 *
 * List products, newest first.
 */
export const productsListProductsInfiniteOptions = (options?: Options<ProductsListProductsData>) => {
    const opts = infiniteQueryOptions<ProductsListProductsResponse, ProductsListProductsError, InfiniteData<ProductsListProductsResponse>, QueryKey<Options<ProductsListProductsData>>, number | Pick<QueryKey<Options<ProductsListProductsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ProductsListProductsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await productsListProducts({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: productsListProductsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Create Product
 *
 * Create a product. New products are always `AVAILABLE`.
 */
export const productsCreateProductMutation = (options?: Partial<Options<ProductsCreateProductData>>): UseMutationOptions<ProductsCreateProductResponse, ProductsCreateProductError, Options<ProductsCreateProductData>> => {
    const mutationOptions: UseMutationOptions<ProductsCreateProductResponse, ProductsCreateProductError, Options<ProductsCreateProductData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await productsCreateProduct({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const productsGetProductQueryKey = (options: Options<ProductsGetProductData>) => createQueryKey('productsGetProduct', options);

/**
 * Get Product
 */
export const productsGetProductOptions = (options: Options<ProductsGetProductData>) => queryOptions<ProductsGetProductResponse, ProductsGetProductError, ProductsGetProductResponse, ReturnType<typeof productsGetProductQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await productsGetProduct({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: productsGetProductQueryKey(options)
});

/**
 * Create Order
 *
 * Create an order and reserve the product (`AVAILABLE` → `RESERVED`).
 */
export const ordersCreateOrderMutation = (options?: Partial<Options<OrdersCreateOrderData>>): UseMutationOptions<OrdersCreateOrderResponse, OrdersCreateOrderError, Options<OrdersCreateOrderData>> => {
    const mutationOptions: UseMutationOptions<OrdersCreateOrderResponse, OrdersCreateOrderError, Options<OrdersCreateOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersCreateOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Pay Order
 *
 * Pay for the order and sell the product (`RESERVED` → `SOLD`). Returns the sold product.
 */
export const ordersPayOrderMutation = (options?: Partial<Options<OrdersPayOrderData>>): UseMutationOptions<OrdersPayOrderResponse, OrdersPayOrderError, Options<OrdersPayOrderData>> => {
    const mutationOptions: UseMutationOptions<OrdersPayOrderResponse, OrdersPayOrderError, Options<OrdersPayOrderData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ordersPayOrder({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const healthHealthQueryKey = (options?: Options<HealthHealthData>) => createQueryKey('healthHealth', options);

/**
 * Health
 */
export const healthHealthOptions = (options?: Options<HealthHealthData>) => queryOptions<HealthHealthResponse, DefaultError, HealthHealthResponse, ReturnType<typeof healthHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await healthHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthHealthQueryKey(options)
});
