// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthHealthData, HealthHealthResponses, OrdersCreateOrderData, OrdersCreateOrderErrors, OrdersCreateOrderResponses, OrdersPayOrderData, OrdersPayOrderErrors, OrdersPayOrderResponses, ProductsCreateProductData, ProductsCreateProductErrors, ProductsCreateProductResponses, ProductsGetProductData, ProductsGetProductErrors, ProductsGetProductResponses, ProductsListProductsData, ProductsListProductsErrors, ProductsListProductsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Products
 *
 * List products, newest first.
 */
export const productsListProducts = <ThrowOnError extends boolean = false>(options?: Options<ProductsListProductsData, ThrowOnError>): RequestResult<ProductsListProductsResponses, ProductsListProductsErrors, ThrowOnError> => (options?.client ?? client).get<ProductsListProductsResponses, ProductsListProductsErrors, ThrowOnError>({ url: '/products', ...options });

/**
 * Create Product
 *
 * Create a product. New products are always `AVAILABLE`.
 */
export const productsCreateProduct = <ThrowOnError extends boolean = false>(options: Options<ProductsCreateProductData, ThrowOnError>): RequestResult<ProductsCreateProductResponses, ProductsCreateProductErrors, ThrowOnError> => (options.client ?? client).post<ProductsCreateProductResponses, ProductsCreateProductErrors, ThrowOnError>({
    url: '/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Product
 */
export const productsGetProduct = <ThrowOnError extends boolean = false>(options: Options<ProductsGetProductData, ThrowOnError>): RequestResult<ProductsGetProductResponses, ProductsGetProductErrors, ThrowOnError> => (options.client ?? client).get<ProductsGetProductResponses, ProductsGetProductErrors, ThrowOnError>({ url: '/products/{product_id}', ...options });

/**
 * Create Order
 *
 * Create an order and reserve the product (`AVAILABLE` → `RESERVED`).
 */
export const ordersCreateOrder = <ThrowOnError extends boolean = false>(options: Options<OrdersCreateOrderData, ThrowOnError>): RequestResult<OrdersCreateOrderResponses, OrdersCreateOrderErrors, ThrowOnError> => (options.client ?? client).post<OrdersCreateOrderResponses, OrdersCreateOrderErrors, ThrowOnError>({
    url: '/orders',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Pay Order
 *
 * Pay for the order and sell the product (`RESERVED` → `SOLD`). Returns the sold product.
 */
export const ordersPayOrder = <ThrowOnError extends boolean = false>(options: Options<OrdersPayOrderData, ThrowOnError>): RequestResult<OrdersPayOrderResponses, OrdersPayOrderErrors, ThrowOnError> => (options.client ?? client).post<OrdersPayOrderResponses, OrdersPayOrderErrors, ThrowOnError>({ url: '/orders/{order_id}/pay', ...options });

/**
 * Health
 */
export const healthHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthData, ThrowOnError>): RequestResult<HealthHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
