// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OrderCreate
 */
export type OrderCreate = {
    /**
     * Product Id
     */
    product_id: string;
};

/**
 * OrderRead
 */
export type OrderRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Price
     */
    price: number | string;
};

/**
 * ProductRead
 */
export type ProductRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Price
     */
    price: string;
    status: ProductStatus;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ProductStatus
 */
export type ProductStatus = 'AVAILABLE' | 'RESERVED' | 'SOLD';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ProductsListProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/products';
};

export type ProductsListProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsListProductsError = ProductsListProductsErrors[keyof ProductsListProductsErrors];

export type ProductsListProductsResponses = {
    /**
     * Response Products-List Products
     *
     * Successful Response
     */
    200: Array<ProductRead>;
};

export type ProductsListProductsResponse = ProductsListProductsResponses[keyof ProductsListProductsResponses];

export type ProductsCreateProductData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/products';
};

export type ProductsCreateProductErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsCreateProductError = ProductsCreateProductErrors[keyof ProductsCreateProductErrors];

export type ProductsCreateProductResponses = {
    /**
     * Successful Response
     */
    201: ProductRead;
};

export type ProductsCreateProductResponse = ProductsCreateProductResponses[keyof ProductsCreateProductResponses];

export type ProductsGetProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/products/{product_id}';
};

export type ProductsGetProductErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsGetProductError = ProductsGetProductErrors[keyof ProductsGetProductErrors];

export type ProductsGetProductResponses = {
    /**
     * Successful Response
     */
    200: ProductRead;
};

export type ProductsGetProductResponse = ProductsGetProductResponses[keyof ProductsGetProductResponses];

export type OrdersCreateOrderData = {
    body: OrderCreate;
    path?: never;
    query?: never;
    url: '/orders';
};

export type OrdersCreateOrderErrors = {
    /**
     * Product not found
     */
    404: ErrorResponse;
    /**
     * Product is already reserved or sold
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrdersCreateOrderError = OrdersCreateOrderErrors[keyof OrdersCreateOrderErrors];

export type OrdersCreateOrderResponses = {
    /**
     * Successful Response
     */
    201: OrderRead;
};

export type OrdersCreateOrderResponse = OrdersCreateOrderResponses[keyof OrdersCreateOrderResponses];

export type OrdersPayOrderData = {
    body?: never;
    path: {
        /**
         * Order Id
         */
        order_id: string;
    };
    query?: never;
    url: '/orders/{order_id}/pay';
};

export type OrdersPayOrderErrors = {
    /**
     * Order not found
     */
    404: ErrorResponse;
    /**
     * Order is already paid
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrdersPayOrderError = OrdersPayOrderErrors[keyof OrdersPayOrderErrors];

export type OrdersPayOrderResponses = {
    /**
     * Successful Response
     */
    200: ProductRead;
};

export type OrdersPayOrderResponse = OrdersPayOrderResponses[keyof OrdersPayOrderResponses];

export type HealthHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthResponses = {
    /**
     * Response Health-Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthResponse = HealthHealthResponses[keyof HealthHealthResponses];
